#!/bin/sh

rootDirectory="$(dirname -- "$0")/.."
source "$rootDirectory/scripts/colours.sh"
export ROOT_DIR="$rootDirectory"

staged_files=$(git diff --cached --name-only --diff-filter=ACMR)


# Run dotnet format on changed files
echo "STAGED FILES" $staged_files

"$rootDirectory/scripts/lint-dotnet.sh" "$staged_files"
"$rootDirectory/scripts/lint-branch-name.sh"



# Check the exit code of the script
if [ $? -ne 0 ]; then
    echo "${RED}Error: Script failed, aborting commit.${NC}"
    exit 1
fi

# Add any modified files to the staging area
git add $staged_files
