global using AutoFixture.Xunit2;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using MongoDB.Driver;
global using SaanSoft.Cqrs.Decorator.Store.MongoDB.GuidIds;
global using SaanSoft.Cqrs.GuidIds.Decorator.Store;
global using SaanSoft.Cqrs.GuidIds.Utilities;
global using SaanSoft.Cqrs.Messages;
global using SaanSoft.Tests.Cqrs.Common.TestModels;
