global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using MongoDB.Driver;
global using SaanSoft.Cqrs.Decorator.Store;
global using SaanSoft.Cqrs.Decorator.Store.MongoDB;
global using SaanSoft.Cqrs.Messages;
global using SaanSoft.Cqrs.Utilities;
global using SaanSoft.Tests.Cqrs.Common.TestModels;
global using SaanSoft.Tests.Cqrs.Decorator.Store.BaseRepository.Repositories;
