global using AutoFixture.Xunit2;
global using FakeItEasy;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using SaanSoft.Cqrs.Bus;
global using SaanSoft.Tests.Cqrs.Common;
global using SaanSoft.Tests.Cqrs.Common.AutoFixture;
global using SaanSoft.Tests.Cqrs.Common.TestModels;
global using SaanSoft.Tests.Cqrs.Common.Utilities;
