on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      dotnet-version:
        required: false
        type: string
        default: "8.0"

permissions:
  checks: write

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --filter FullyQualifiedName~SaanSoft.Tests --logger "trx;LogFileName=unit-test-results.trx" --results-directory reports

      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          # Name of the check run which will be created
          name: Unit test results (${{ inputs.runs-on }} - ${{ inputs.dotnet-version }})
          path: "reports/*.trx"
          reporter: dotnet-trx
          fail-on-error: true
