name: ci-cd

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Directory.*.props"

permissions:
  contents: read

jobs:
  ci-cd:
    permissions:
      contents: write
      packages: write
    uses: saan800/github/.github/workflows/_dotnet-build-test-pack-publish.yml@main
    with:
      os: ubuntu-latest
      dotnet-version: 9.0.x
      codecov-slug: "saan800/saansoft-cqrs"
      is-release: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # TODO: uncomment when ready to release NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
