name: CI

on:
  pull_request:
    # paths:
    # - '**.cs'
    # - '**.csproj'
    # - '**.json'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}-${{matrix.dotnet-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        # dotnet-version: ['6.0', '7.0', '8.0']
        os: [ubuntu-latest]
        dotnet-version: ['8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --filter FullyQualifiedName~SaanSoft.Tests --logger trx --results-directory "test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}
          path: test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}.xml
        if: ${{ always() }}



jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Upload test report
        uses: dorny/test-reporter@v1
        with:
          name: dotnet-tests                # Name of the check run which will be created
          artifact: /test-results-(.*)/     # artifact name
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results