name: lint

on: pull_request

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Get changed c# files
        id: changed-csharp-files
        uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45.0.5
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.cs

      - name: Setup linting config
        id: config
        env:
          hasChangedCSharpFiles: ${{ steps.changed-csharp-files.outputs.any_changed == 'true' }}
        run: |
          if [ "${hasChangedCSharpFiles}" == "true" ]; then
            echo "VALIDATE_ALL_CODEBASE=false" >> "$GITHUB_OUTPUT"
          else
            echo "VALIDATE_ALL_CODEBASE=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run super-linter
        uses: super-linter/super-linter@1fa6ba58a88783e9714725cf89ac26d53e80c148 # v6.9.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (./\.editorconfig|\.idea/*|\.vscode/*)
          IGNORE_GENERATED_FILES: true
          # false -> only checks changed files
          VALIDATE_ALL_CODEBASE: ${{ steps.config.outputs.VALIDATE_ALL_CODEBASE  == 'true'}}
          VALIDATE_CSHARP: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true

  spellcheck:
    permissions:
      contents: read # for streetsidesoftware/cspell-action to fetch files for commit
      pull-requests: read # for streetsidesoftware/cspell-action to fetch commits for PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@ef95dc49d631fc2a9e9ea089ae2b2127b7c4588e # v6.10.0
        with:
          config: .cspell.json
          check_dot_files: false
          incremental_files_only: true
