name: lint

on: pull_request

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Get changed c# files
        id: changed-csharp-files
        uses: tj-actions/changed-files@1754cd4b9e661d1f0eced3b33545a8d8b3bc46d8 # v44.5.0
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.cs

      - name: Setup linting config
        id: config
        run: |
          if [ "${hasChangedCSharpFiles}" == "true" ]; then
            echo "VALIDATE_ALL_CODEBASE=false" >> "$GITHUB_OUTPUT"
          else
            echo "VALIDATE_ALL_CODEBASE=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          hasChangedCSharpFiles: ${{ steps.changed-csharp-files.outputs.any_changed == 'true' }}

      - name: Run super-linter
        uses: super-linter/super-linter@56576d491db07c7236b445ab09991ca49d12b0c6 # v6.5.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (./\.editorconfig|\.idea/*|\.vscode/*)
          IGNORE_GENERATED_FILES: true
          # false -> only checks changed files
          VALIDATE_ALL_CODEBASE: ${{ steps.config.outputs.VALIDATE_ALL_CODEBASE  == 'true'}}
          VALIDATE_CSHARP: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true

  spellcheck:
    permissions:
      contents: read  # for streetsidesoftware/cspell-action to fetch files for commit
      pull-requests: read  # for streetsidesoftware/cspell-action to fetch commits for PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@104110db58e8c9a11c1c6be025e2082f4dded3bb # v6.3.0
        with:
          config: .cspell.json
          check_dot_files: false
          incremental_files_only: true

