name: pr

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: saan800/github/.github/workflows/_pr-labeler.yml@main
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-lint:
    permissions:
      contents: read
    uses: saan800/github/.github/workflows/_pr-lint.yml@main
    with:
      run-lint: true
      cspell-config: .cspell.json
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
