name: Validate dotnet

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  dotnet-build-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['2.1', '2.2', '3.0', '3.1', '5.0', '6.0', '7.0', '8.0']

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: dotnet - setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # You can test your matrix by printing the current dotnet version
      - name: dotnet - display version
        run: dotnet --version

      - name: nuget - cache packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: dotnet - restore packages
        run: dotnet restore

      - name: dotnet - build
        run: dotnet build --no-restore

      - name: dotnet - run unit tests
        run: dotnet test --no-build --filter FullyQualifiedName~SaanSoft.Tests